In [1]:
import pandas as pd
import numpy as np

In [2]:
students = [
    [86, 'M', 'verygood'],
    [95, 'F', 'excellent'],
    [75, None, 'good'],
    [np.nan, 'M', 'average'],
    [71, 'M', 'good'],
    [np.nan, None, 'verygood'],
    [92, 'F', 'verygood'],
    [99, 'M', 'excellent']
]

In [3]:
dfstud = pd.DataFrame(students)
dfstud.columns = ['marks', 'gender', 'result']
dfstud

,marks,gender,result
0,86.0,M,verygood
1,95.0,F,excellent
2,75.0,None,good
3,NaN,M,average
4,71.0,M,good
5,NaN,None,verygood
6,92.0,F,verygood
7,99.0,M,excellent


In [4]:
dfstud.isnull().values.sum()

np.int64(4)

In [5]:
X = dfstud.iloc[:, 0:2].values
y = dfstud.iloc[:, 2].values
type(X)

numpy.ndarray

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 0:1] = imputer.fit_transform(X[:, 0:1])
print(X)

[[86.0 'M']
 [95.0 'F']
 [75.0 None]
 [86.33333333333333 'M']
 [71.0 'M']
 [86.33333333333333 None]
 [92.0 'F']
 [99.0 'M']]


In [7]:
imputer = SimpleImputer(missing_values=None, strategy='constant', fill_value='M')
X[:, 1:2] = imputer.fit_transform(X[:, 1:2])
print(X)

[[86.0 'M']
 [95.0 'F']
 [75.0 'M']
 [86.33333333333333 'M']
 [71.0 'M']
 [86.33333333333333 'M']
 [92.0 'F']
 [99.0 'M']]


Conclusion: We can use Sklearn.impute class SimpleImputer to impute missing values for both numerical and categorical features. For numerical missing values a strategy such as mean, median, most freq. and constant can be used. For categorical features a strategy such as most frequent and constant can be used.

In [8]:
import pandas as pd
import numpy as np

In [9]:
ds = pd.read_csv('/content/CountryAgeSalary.csv')
ds

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [10]:
X = ds.iloc[:, :-1].values
y = ds.iloc[:, 3].values

In [11]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:2] = imputer.fit_transform(X[:, 1:2])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
X[:, 2:3] = imputer.fit_transform(X[:, 2:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Conclusion: We can use Sklearn.impute class SimpleImputer to impute missing values for both numerical features on imported datasets. For numerical missing values a strategy such as mean, median, most freq. and constant can be used.

In [13]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 61000.0]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columntransformer = ColumnTransformer(
    [('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

X = np.array(columntransformer.fit_transform(X), dtype=str)
print(X)

[['1.0' '0.0' '0.0' '44.0' '72000.0']
 ['0.0' '0.0' '1.0' '27.0' '48000.0']
 ['0.0' '1.0' '0.0' '30.0' '54000.0']
 ['0.0' '0.0' '1.0' '38.0' '61000.0']
 ['0.0' '1.0' '0.0' '40.0' '61000.0']
 ['1.0' '0.0' '0.0' '35.0' '58000.0']
 ['0.0' '0.0' '1.0' '38.77777777777778' '52000.0']
 ['1.0' '0.0' '0.0' '48.0' '79000.0']
 ['0.0' '1.0' '0.0' '50.0' '83000.0']
 ['1.0' '0.0' '0.0' '37.0' '67000.0']]


Conclusion: LabelEncoder is used when the categorical data is ordinal i.e. it has a specific order and we have large number of categorical values available. OneHotEncoder is used when the categorical data is not ordinal and the categories are less.

In [15]:
X1 = X[:, 3:5]

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(X1)

df_MinMax = pd.DataFrame(scaled_features, columns=['Age', 'Salary'])
df_MinMax

,Age,Salary
0,0.739130,0.685714
1,0.000000,0.000000
2,0.130435,0.171429
3,0.478261,0.371429
4,0.565217,0.371429
5,0.347826,0.285714
6,0.512077,0.114286
7,0.913043,0.885714
8,1.000000,1.000000
9,0.434783,0.542857


In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
sc_X = scaler.fit_transform(X1)

sc_X = pd.DataFrame(sc_X, columns=['Age', 'Salary'])
sc_X

,Age,Salary
0,0.758874,0.772568
1,-1.711504,-1.408800
2,-1.275555,-0.863458
3,-0.113024,-0.227226
4,0.177609,-0.227226
5,-0.548973,-0.499897
6,0.000000,-1.045239
7,1.340140,1.408800
8,1.630773,1.772361
9,-0.258340,0.318116


Conclusion: Standardization is used when features have different scales and the model assumes data is normally distributed as Gaussian Distribution. Normalization is used when features need to be scaled to a fixed range like 0–1 and not normally distributed.